---
language: ruby
bundler_args: --without beaker
rvm:
  - 2.5
env:
  - PUPPET_GEM_VERSION="~> 5.0"
  - PUPPET_GEM_VERSION="~> 6.0"
matrix:
  include:
  - rvm: 2.5
    bundler_args: --without release
    env: BEAKER_set=centos-7-docker BEAKER_HYPERVISOR=docker bundle exec rake beaker
    services: docker
notifications:
  email: false
